package com.speedystone.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import aiterminal.android.chdmc.com.aiterminal.bean.NewsListItemBean;
import aiterminal.android.chdmc.com.aiterminal.bean.UserInfo;

import com.speedystone.greendaodemo.db.NewsListItemBeanDao;
import com.speedystone.greendaodemo.db.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsListItemBeanDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final NewsListItemBeanDao newsListItemBeanDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsListItemBeanDaoConfig = daoConfigMap.get(NewsListItemBeanDao.class).clone();
        newsListItemBeanDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        newsListItemBeanDao = new NewsListItemBeanDao(newsListItemBeanDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(NewsListItemBean.class, newsListItemBeanDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        newsListItemBeanDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public NewsListItemBeanDao getNewsListItemBeanDao() {
        return newsListItemBeanDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
